### ISSUE TITLE
author list

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/scipy2019-pmda-data#1]
@kain88-de @iparask @mimischi @richardjgowers : Shujie (@VOD555 ) is going to submit an abstract on pmda for [SciPy 2019](https://www.scipy2019.scipy.org/). If accepted it will also give us an opportunity to write a short conference proceedings on pmda.

We added every contributor to pmda on the author list. Please see [00_Fan.rst](https://github.com/Becksteinlab/Scipy2019/blob/master/00_Fan.rst).

1. Do you want to be an author on this contribution?
2. Do you agree with the author order?
3. Is your affiliation correctly captured?
3. Do you have suggestions for changes to the abstract?
4. Any other comments?

Regarding author order: Max really has done the majority of the work on the core of PMDA and if this were a normal paper I would immediately place Max first but because Shujie is actually presenting the work, I feel that he should go first. However, this is a difficult discussion and I welcome a discussion.

**Comment by orbeckst** [comment]
Forgot to say: This has to be submitted by Friday 15 Feb so please comment soon!

**Comment by richardjgowers** [comment]
@orbeckst Yes, Mostly yes, Yes, I'll suggest via PR, No other comments

Author order is tricky, but I see the logic that Shujie is presenting and making this presentation of pmda happen.

**Comment by iparask** [comment]
Hello @orbeckst, thank you for adding me in the author list. I am not sure if I will find the time to contribute to this paper, though, since the deadline is so close and I do not want to delay you without reason.

Feel free to do what you think is best!

Giannis

**Comment by orbeckst** [comment]
@iparask I can't make a decision for you: As an author you would have the responsibility to stand behind whatever is submitted and published. Even though you might not have to write the paper you still have to read it and agree to it. It's up to you to decide what kind of effort that will entail and what you can afford. 

I can say that I am not planning on dumping the writing on you. But I would expect you being responsive to questions, especially during the review phase or if issues with code come up.

Sorry to be blunt but I need you to tell us what you want to do.

**Comment by mimischi** [comment]
@orbeckst Thanks for adding me to the authors list and I'm OK with the order. I would be available in helping with the manuscript and revisions! Will also submit a short PR with some comments.

Edit: Opened #3 for some minor things.

**Comment by kain88-de** [comment]
I’m good with it. I don’t mind not being the first author. Have fun at
SciPy!

**Comment by iparask** [comment]
@orbeckst then I am okay with being in the author list, I do not mind with the order and thank you again! I will read it tomorrow morning then and leave comments or submit a PR!

**Comment by orbeckst** [comment]
I think everybody is on board so you can submit @VOD555 !
